version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Kiev"
    open-pull-requests-limit: 5
    groups:
      test-dependencies:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.collector"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Kiev"
    open-pull-requests-limit: 5
